# Generated by Django 5.2.3 on 2025-06-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_coupon_quantity_alter_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='size',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
