# Generated by Django 5.2.3 on 2025-06-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_orderitems_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='coupon_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReferralReward',
        ),
    ]
