# Generated by Django 5.2.3 on 2025-06-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_orderitems_coupon_price_delete_referralreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
